// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCay-GWKD_sGPnYyOaM76acu_m1vfP8UuI',
    appId: '1:457719344782:web:156af8de4e2060f8a923df',
    messagingSenderId: '457719344782',
    projectId: 'sidipo-apps',
    authDomain: 'sidipo-apps.firebaseapp.com',
    storageBucket: 'sidipo-apps.firebasestorage.app',
    measurementId: 'G-WGNZZDLKSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4P35jyQhpufxaGzfdCLp_ldQ8fxJTF8',
    appId: '1:457719344782:android:a64569c56f6a72aea923df',
    messagingSenderId: '457719344782',
    projectId: 'sidipo-apps',
    storageBucket: 'sidipo-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDXvrfa-LffgBPgj2s8FApjkEnWRCZYY',
    appId: '1:457719344782:ios:b04ec588cf145e3da923df',
    messagingSenderId: '457719344782',
    projectId: 'sidipo-apps',
    storageBucket: 'sidipo-apps.firebasestorage.app',
    iosBundleId: 'com.example.sidipoApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDXvrfa-LffgBPgj2s8FApjkEnWRCZYY',
    appId: '1:457719344782:ios:b04ec588cf145e3da923df',
    messagingSenderId: '457719344782',
    projectId: 'sidipo-apps',
    storageBucket: 'sidipo-apps.firebasestorage.app',
    iosBundleId: 'com.example.sidipoApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCay-GWKD_sGPnYyOaM76acu_m1vfP8UuI',
    appId: '1:457719344782:web:1b9f80791fa9f93ba923df',
    messagingSenderId: '457719344782',
    projectId: 'sidipo-apps',
    authDomain: 'sidipo-apps.firebaseapp.com',
    storageBucket: 'sidipo-apps.firebasestorage.app',
    measurementId: 'G-DVSVWLLG5E',
  );
}
