// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvksLsntJ6BECroUmWIIePGMNgFH1spA',
    appId: '1:957970938061:web:110afd356dbe8bf995d184',
    messagingSenderId: '957970938061',
    projectId: 'sidipo-apps-d215e',
    authDomain: 'sidipo-apps-d215e.firebaseapp.com',
    storageBucket: 'sidipo-apps-d215e.firebasestorage.app',
    measurementId: 'G-4R62FTCY1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1oJn3dTuX7ozcZMIX3ToB7YVp2vJ5XSw',
    appId: '1:957970938061:android:30f3dc070231ba6b95d184',
    messagingSenderId: '957970938061',
    projectId: 'sidipo-apps-d215e',
    storageBucket: 'sidipo-apps-d215e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9av2vWuEkiag-LZBcym2yhAgpMzhBR8',
    appId: '1:957970938061:ios:af1be8b168b0d7bb95d184',
    messagingSenderId: '957970938061',
    projectId: 'sidipo-apps-d215e',
    storageBucket: 'sidipo-apps-d215e.firebasestorage.app',
    iosBundleId: 'com.example.posyanduDigitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq9av2vWuEkiag-LZBcym2yhAgpMzhBR8',
    appId: '1:957970938061:ios:af1be8b168b0d7bb95d184',
    messagingSenderId: '957970938061',
    projectId: 'sidipo-apps-d215e',
    storageBucket: 'sidipo-apps-d215e.firebasestorage.app',
    iosBundleId: 'com.example.posyanduDigitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXvksLsntJ6BECroUmWIIePGMNgFH1spA',
    appId: '1:957970938061:web:3ecd5b33c2b5daa095d184',
    messagingSenderId: '957970938061',
    projectId: 'sidipo-apps-d215e',
    authDomain: 'sidipo-apps-d215e.firebaseapp.com',
    storageBucket: 'sidipo-apps-d215e.firebasestorage.app',
    measurementId: 'G-NCBX0C3PVB',
  );
}
